export type PrivateUser = any;
export type PublicUser = any;
export type PermissionType = any;
export type AuthAuthEntity = any;
export type DataBoostersEntity = any;
export type MarketOpenPackDto = any;
export type UserBlook = any;
export type Blook = any;
export type Config = any;
export type Banner = any;
export type Emoji = any;
export type Font = any;
export type Item = any;
export type ItemShop = any;
export type Pack = any;
export type Rarity = any;
export type SpinnyWheel = any;
export type StripeProductEntity = any;
export type StripeStoreEntity = any;
export type Title = any;
export type ImageOrVideo = any;
export type Username = any;
export type AuctionsAuctionEntity = any;
export type AuctionsBidAuctionDto = any;
export type AuctionsBuyAuctionDto = any;
export type AuctionsCreateAuctionDto = any;
export type AuctionsRecentAveragePriceEntity = any;
export type AuctionsRecentAveragePriceDto = any;
export type AuctionsSearchAuctionDto = any;
export type AuthOtpEntity = any;
export type UserWebAuthn = any;
export type BlooksSellBlookDto = any;
export type ChatEditMessageDto = any;
export type Message = any;
export type ChatCreateMessageDto = any;
export type CosmeticsChangeAvatarDto = any;
export type CosmeticsUploadAvatarDto = any;
export type CosmeticsChangeBannerDto = any;
export type CosmeticsUploadBannerDto = any;
export type CosmeticsChangeColorTier1Dto = any;
export type CosmeticsChangeColorTier2Dto = any;
export type CosmeticsChangeFontDto = any;
export type CosmeticsChangeTitleDto = any;
export type DiscordLinkDto = any;
export type SettingsDisableOtpDto = any;
export type SettingsEnableOtpDto = any;
export type SettingsChangeChatColorDto = any;
export type SettingsChangePasswordDto = any;
export type SettingsChangeSettingDto = any;
export type SettingsChangeUsernameDto = any;
export type StripeCreatePaymentMethodDto = any;
export type StripeCreateSetupIntentDto = any;
export type StripeCreateSetupIntentEntity = any;
export type Transaction = any;
export type S3UploadEntity = any;
export type Upload = any;
export type SocketAuctionBidEntity = any;
export type SocketAuctionExpireEntity = any;
export type SocketFriendsEntity = any;
export type FriendsFriendsEntity = any;
export type Resource = any;
export type User = any;
export type UserItem = any;
export type UserPaymentMethod = any;
export type RarityAnimationType = any;
export type SocketMessageType = any;
export type EntityType = any;
export type Mode = any;
export type PermissionTypeEnum = any;

export declare const EntityType: any;
export declare const Mode: any;
export declare const PermissionTypeEnum: any;
export declare const RarityAnimationTypeEnum: any;
export declare const SocketMessageType: any;
export declare const Forbidden: any;
export declare const experienceToLevel: (experience: number) => number;
export declare const levelToExperienceRemaining: (experience: number) => number;

export declare const NotFound: {
    UNKNOWN_USER: string;
};

export declare const AuctionTypeEnum: {
    BLOOK: string;
    ITEM: string;
};

export declare const ItemShopItemTypeEnum: any;
export declare const SettingFriendRequestEnum: any;
export declare const CurrencyTypeEnum: any;
export declare const TransactionStatusEnum: any;