export enum SocketMessageType {
    UNAUTHORIZED = "UNAUTHORIZED",
    AUTHORIZED = "AUTHORIZED",

    PING = "PING",
    PONG = "PONG",

    NOTIFICATION = "NOTIFICATION",

    USER_UPDATED = "USER_UPDATED",

    PURCHASE_SUCCEEDED = "PURCHASE_SUCCEEDED",

    CHAT_MESSAGES_CREATE = "CHAT_MESSAGES_CREATE",
    CHAT_MESSAGES_UPDATE = "CHAT_MESSAGES_UPDATE",
    CHAT_MESSAGES_DELETE = "CHAT_MESSAGES_DELETE",
    CHAT_TYPING_STARTED = "CHAT_TYPING_STARTED",

    AUCTIONS_EXPIRE = "AUCTIONS_EXPIRE",
    AUCTIONS_BID = "AUCTIONS_BID",

    TRADING_PLAZA_JOIN = "TRADING_PLAZA_JOIN",
    TRADING_PLAZA_LEAVE = "TRADING_PLAZA_LEAVE",
    TRADING_PLAZA_MOVE = "TRADING_PLAZA_MOVE",

    FRIENDS_REQUEST_RECEIVED = "FRIENDS_REQUEST_RECEIVED",
    FRIENDS_REQUEST_DECLINED = "FRIENDS_REQUEST_DECLINED",
    FRIENDS_REQUEST_REMOVED = "FRIENDS_REQUEST_REMOVED",
    FRIENDS_REMOVED = "FRIENDS_REMOVED",

    LAGBACK = "LAGBACK",
    ERROR = "ERROR"
}
